<div class="col-md-12">
    <div class="card ">
        <div class="card-header row">
            <div class="card-header col ">
                <h3 class="card-title"> Estoque </h3>
            </div>
            <div class="card-header col-5 row ">
                <div class="col-6 mx-0 px-0 ">
                    <a class="btn btn-primary" href="/application/entradaEstoque">
                        ENTRADA
                    </a>
                </div>
                <div class="col-6 mx-0 px-0 ">
                    <a class="btn btn-primary" href="/application/saidaEstoque">
                        SAIDA
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                            <th>
                                Nome
                            </th>
                            <th>
                                Quantidade
                            </th>
                            </th>
                            <th>
                                Média Valor
                            </th>
                        </tr>
                    </thead>
                    <tbody id="produtoTable">
                        <tr>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    const loadProduto = () => {
        $('#produtoTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)

        let url = '/api/estoque';
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#produtoTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            $('#produtoTable').html('')

            dados.map(produto => {
                console.log(produto)
                $('#produtoTable').prepend(`<tr>
                            <td id="nome${produto.id}">${produto.nome}</td>
                            <td>
                            ${produto.qtde}
                            </td>
                            <td>
                            R$${produto.valor_unitario}
                            </td>
                            <td>

                                <i onClick="editarProduto(${produto.id},'${produto.nome}','${produto.id_medida}','${produto.id_categoria}')" class="tim-icons text-warning icon-pencil tim-icons-lg click" data-bs-toggle="modal" data-bs-target="#estoqueProdutoModal"></i>
                                <i onClick="removerProduto(${produto.id})" class="tim-icons text-danger icon-trash-simple tim-icons-lg click"></i>
                            </td>
                        </tr>`)
            })

        })

    }


    $(document).ready(() => {

        loadProduto()
    })
</script>