<?php

$fornecedor = $this->fornecedor;


$produtoForm = $this->produtoForm;
$produtoForm->prepare();
$produtoForm->setAttribute('method', 'post');

$nome = $produtoForm->get('produto');
$nome->setAttributes(['class' => 'form-control  text-dark']);
$nome->setAttributes(['placeholder' => 'fornecedor...']);
$nome->setAttributes(['required' => 'true']);
$fornecedorhidden = $produtoForm->get('fornecedorhidden');
$fornecedorhidden->setAttributes(['value' => $fornecedor]);

$valor = $produtoForm->get('valor');
$valor->setAttributes(['class' => 'form-control  text-dark']);
$valor->setAttributes(['placeholder' => 'Valor...']);
$valor->setAttributes(['id' => 'valor']);
$valor->setAttributes(['required' => 'true']);

$send = $produtoForm->get('send');
$send->setAttributes(['class' => 'btn btn-primary float-right']);
$send->setAttributes(['id' => 'enviar']);


?>




<div class="col-md-12">
    <div class="card ">
        <div class="card-header row">
            <div class="card-header col ">
                <h3 class="card-title" id="forncededorTitle"> Fornecedores </h3>
            </div>
            <div class="card-header col-3 mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#produtoModal">
                    <i class="tim-icons icon-bag-16 tim-icons-lg"></i> ADICIONAR PRODUTO
                </button>
            </div>
            <div class="card-header col-3 mx-0 px-0">
                <a class="btn btn-secondary" href="/application/listaFornecedor">
                    VOLTAR
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                            <th>
                                Nome
                            </th>
                            <th>
                                Valor
                            </th>
                            <th>
                                Medida
                            </th>
                            <th>
                                Categoria
                            </th>
                        </tr>
                    </thead>
                    <tbody id="produtosTable">
                        <tr>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="produtoModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="produtoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?= $this->form()->openTag($produtoForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="produtoModalLabel">Adicionar Produto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formElement($fornecedorhidden); ?>
                    <?= $this->formLabel($nome); ?>
                    <?= $this->formElement($nome); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($valor); ?>
                    <?= $this->formElement($valor); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="closeProdutoModal" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <?= $this->formElement($send); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    const loadProdutos = (fornecedor) => {
        $('#produtosTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)

        let url = '/api/listaFornecedor/' + fornecedor;
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#produtosTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            $('#produtosTable').html('')
            dados.map(produto => {
                $('#forncededorTitle').html(produto.fornecedor)
                $('#produtosTable').prepend(`<tr>
                            <td>
                                ${produto.nome}
                            </td>
                            <td>
                             R$ ${produto.valor}
                            </td>
                            <td>
                            ${produto.quantidade} ${produto.medida}
                            </td>
                            <td>
                            ${produto.categoria}
                            </td>
                            <td>
                            <i onClick="removerProduto(${fornecedor},${produto.id})" class="tim-icons text-danger icon-trash-simple tim-icons-lg click"></i>
                            </td>
                        </tr>`)
            })

        })

    }
    const removerProduto = (fornecedor, produto) => {
        let url = '/api/removerProdutoFornecedor/' + fornecedor + '/' + produto;
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#produtosTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            if (dados.success == 1) {
                Swal.fire(
                    'Eeeeee!',
                    'Produto Removido!',
                    'success'
                )
                $('#closeProdutoModal').click();
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produto Não Removido!',
                    'error'
                )
            }

            loadProdutos(fornecedor)
        })
    }
    $('#produtoForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('produtoForm')
        let formData = new FormData(form)
        let url = '/api/insertProdutoFornecedor';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                Swal.fire(
                    'Eeeeee!',
                    'Produto Adicionado!',
                    'success'
                )
                $('#closeProdutoModal').click();
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produto Não Adicionado!',
                    'error'
                )
            }

            loadProdutos(<?= $fornecedor ?>)
        }).fail(function(e) {
            console.log(e);
        });

    })


    $(document).ready(() => {

        loadProdutos(<?= $fornecedor ?>)
        $('#valor').maskMoney();
    })
</script>