<?php

$fornecedorForm = $this->fornecedorForm;
$fornecedorForm->prepare();
$fornecedorForm->setAttribute('method', 'post');

$nomeFornecedor = $fornecedorForm->get('nome');
$nomeFornecedor->setAttributes(['class' => 'form-control  text-dark']);
$nomeFornecedor->setAttributes(['placeholder' => 'fornecedor...']);
$nomeFornecedor->setAttributes(['required' => 'true']);

$sendFornecedor = $fornecedorForm->get('send');
$sendFornecedor->setAttributes(['class' => 'btn btn-primary float-right']);
$sendFornecedor->setAttributes(['id' => 'enviarFornecedor']);


?>




<div class="col-md-12">
    <div class="card ">
        <div class="card-header row">
            <div class="card-header col ">
                <h3 class="card-title"> Fornecedores </h3>
            </div>
            <div class="card-header col-3 mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#fornecedorModal">
                    <i class="tim-icons icon-bus-front-12 tim-icons-lg"></i> FORNECEDOR +
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                            <th>
                                Nome
                            </th>
                            <th>
                                Produtos
                            </th>
                        </tr>
                    </thead>
                    <tbody id="fornecedorTable">
                        <tr>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="fornecedorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="fornecedorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?= $this->form()->openTag($fornecedorForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="fornecedorModalLabel">NOVO FORNECEDOR</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <input type="hidden" id="editInput" value="0">
                <input type="hidden" id="idFornecedor" name="id">
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formLabel($nomeFornecedor); ?>
                    <?= $this->formElement($nomeFornecedor); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="closeFornecedorModal" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <?= $this->formElement($sendFornecedor); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    const loadFornecedores = () => {
        $('#fornecedorTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)

        let url = '/api/listaFornecedores';
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#fornecedorTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            $('#fornecedorTable').html('')

            dados.map(fornecedor => {

                let remover = ''

                if (fornecedor.qtd == 0) {
                    remover = `<i onClick="removerFornecedor(${fornecedor.id})" class="tim-icons text-danger icon-trash-simple tim-icons-lg click"></i>`
                }
                $('#fornecedorTable').prepend(`<tr>
                            <td>
                                ${fornecedor.nome}
                            </td>
                            <td>
                            ${fornecedor.qtd}
                            </td>
                            <td><a href="/application/fornecedor/${fornecedor.id}">
                            <i class="tim-icons icon-notes"></i></a>
                            
                            </td>
                            <td>
                            <i onClick="editarFornecedor(${fornecedor.id},'${fornecedor.nome}')" class="tim-icons text-warning icon-pencil tim-icons-lg click" data-bs-toggle="modal" data-bs-target="#fornecedorModal"></i>
                                
                            ${remover}
                            </td>

                        </tr>`)
            })

        })

    }

    const limparEditar = () => {
        $('#fornecedorModalLabel').html('NOVO FORNECEDOR')
        $('#editInput').val(0)
        $("input[name='nome']").val('')
        $("select[name='medida']").val('');
        $("input[name='quantidade']").val('')
        $("select[name='categoria']").val('');
    }

    const editarFornecedor = (fornecedor,nome) => {
        
        $('#editInput').val(1)
        $('#idFornecedor').val(fornecedor)
        $("input[name='nome']").val(nome)

        $('#fornecedorModalLabel').html('EDITAR FORNECEDOR')

    }

    $('#fornecedorForm').submit(e => {
        e.preventDefault()
        let editInput = $('#editInput').val()
        let url = ''
        if(editInput == 0){
            url = '/api/insertFornecedor'
        }else{
            url = '/api/updateFornecedor'
        }
        enviarFornecedor(url)

    })

    const enviarFornecedor = (url) => {
        let form = document.getElementById('fornecedorForm')
        let formData = new FormData(form)
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            console.log(e)
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#fornecedorForm input').val("");
                $('#enviarFornecedor').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Fornecedor Cadastrado!',
                    'success'
                )
                $('#closeFornecedorModal').click();
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Fornecedor Não Cadastrado!',
                    'error'
                )
            }

            loadFornecedores()
        }).fail(function(e) {
            console.log(e);
        });
    }


    const removerFornecedor = (fornecedor) => {

        let url = '/api/removerFornecedor/' + fornecedor;
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            console.log(dados)
            $('#fornecedorsTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            console.log(dados)
            if (dados.success == 1) {
                Swal.fire(
                    'Eeeeee!',
                    'Fornecedor Removido!',
                    'success'
                )
                $('#closefornecedorModal').click();
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Fornecedor Não Removido!',
                    'error'
                )
            }

            loadFornecedores()
        })
    }

    $(document).ready(() => {

        loadFornecedores()
        $('#valor').maskMoney();
    })
</script>