<?php

$produtoForm = $this->produtoForm;
$produtoForm->prepare();
$produtoForm->setAttribute('method', 'post');

$nome = $produtoForm->get('produto');
$nome->setAttributes(['class' => 'form-control  text-dark']);
$nome->setAttributes(['id' => 'produtoSelect']);
$nome->setAttributes(['required' => 'true']);
$nome->setAttributes(['multiple' => 'true']);
$nome->setAttributes(['aria-label ' => 'multiple select']);

$send = $produtoForm->get('send');
$send->setAttributes(['class' => 'btn btn-primary float-right']);
$send->setAttributes(['id' => 'enviar']);

?>

<div class="col-12 row p-4" style="min-height: 400px;">
    <div class="col-md-6">
        <div class="card h-100">
            <div class="card-header row">
                <div class="card-header col-10 ">
                    <h3 class="card-title"> Produtos </h3>
                </div>
                <div class="col-md-12">
                    <?= $this->form()->openTag($produtoForm); ?>
                    <?= $this->formElement($nome); ?>
                    <?= $this->formElement($send); ?>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card card-tasks h-100">
            <div class="card-header ">
                <h3 class="title d-inline">Lista</h3>

            </div>
            <div class="card-body ">
                <div class="table-full-width table-responsive">
                    <table class="table">
                        <tbody id="listaTable">
                            <tr>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12 row  p-4" style="min-height: 400px;" id="cardFornecedor">
    <div class="col-lg-12">
        <div class="card card-chart">
            <div class="card-header">
                <h3 class="card-title">Fornecedores</h3>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="CountryChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="listaModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="listaModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="listaModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

            </div>

        </div>
    </div>
</div>



<script>
    var myModal = new bootstrap.Modal(document.getElementById('listaModal'), {
        keyboard: false
    })


    $('#produtoForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('produtoForm')
        let formData = new FormData(form)
        let url = '/api/addListaProduto';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#produtoForm input').val("");
                $('#enviar').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Produtos Cadastrados na Lista!',
                    'success'
                )
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produtos Não Cadastrados na Lista!',
                    'error'
                )
            }

        }).fail(function(e) {
            console.log(e);
        });

    })


    const loadProdutos = () => {
        $('#listaTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)
        let url = '/api/listaProduto';
        $.ajax({
            url: url,
            type: "POST",
        }).done(function(e) {
            let result = JSON.parse(e)

            console.log(result)

            $('#listaTable').html('')
            result.map(produto => {

                $('#listaTable').prepend(`<tr>
                            <td>
                                ${produto.nome}
                            </td>
                            <td>
                            ${produto.fornecedor}
                            </td>
                            <td>
                            R$ ${produto.valor}
                            </td>
                            <td>
                            ${produto.id_medida}
                            </td>
                            <td>
                            ${produto.id_categoria}
                            </td>
                        </tr>`)
            })




        }).fail(function(e) {
            console.log(e);
        });
    }
    const loadFornecedores = () => {
        $('#listaTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)
        let url = '/api/listaProdutoFornecedor/1';
        $.ajax({
            url: url,
            type: "POST",
        }).done(function(e) {
            let result = JSON.parse(e)

            labels = new Array()
            dados = new Array()

            let maiorValor = 0
            result.map(fornecedor => {
                let valorFloat = parseFloat(fornecedor.valor).toFixed(2)
                labels.push(fornecedor.nome)
                dados.push(valorFloat);

                if( maiorValor < valorFloat){
                    maiorValor =  valorFloat
                }

            })

            gradientBarChartConfiguration = {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },

                tooltips: {
                    backgroundColor: '#f5f5f5',
                    titleFontColor: '#333',
                    bodyFontColor: '#666',
                    bodySpacing: 4,
                    xPadding: 12,
                    mode: "nearest",
                    intersect: 0,
                    position: "nearest"
                },
                responsive: true,
                scales: {
                    yAxes: [{

                        gridLines: {
                            drawBorder: false,
                            color: 'rgba(29,140,248,0.1)',
                            zeroLineColor: "transparent",
                        },
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: maiorValor * 2,
                            padding: 20,
                            fontColor: "#9e9e9e"
                        }
                    }],

                    xAxes: [{

                        gridLines: {
                            drawBorder: false,
                            color: 'rgba(29,140,248,0.1)',
                            zeroLineColor: "transparent",
                        },
                        ticks: {
                            padding: 20,
                            fontColor: "#9e9e9e"
                        }
                    }]
                }
            };

            data = {
                labels: labels,
                datasets: [{
                    label: "",
                    fill: true,
                    backgroundColor: gradientStroke,
                    hoverBackgroundColor: gradientStroke,
                    borderColor: '#1f8ef1',
                    borderWidth: 2,
                    borderDash: [],
                    borderDashOffset: 0.0,
                    data: dados,
                }]
            }

            var ctx = document.getElementById("CountryChart").getContext("2d");

            var gradientStroke = ctx.createLinearGradient(0, 230, 0, 50);

            gradientStroke.addColorStop(1, 'rgba(29,140,248,0.2)');
            gradientStroke.addColorStop(0.4, 'rgba(29,140,248,0.0)');
            gradientStroke.addColorStop(0, 'rgba(29,140,248,0)'); //blue colors


            var myChart = new Chart(ctx, {
                type: 'bar',
                responsive: true,
                legend: {
                    display: false
                },
                data: data,
                options: gradientBarChartConfiguration
            });
        }).fail(function(e) {
            console.log(e);
        });
    }

    $('#produtoSelect').addClass('text-white')
    $(document).ready(function() {
        loadProdutos()
        loadFornecedores()
    });
</script>