<?php

$produtoForm = $this->produtoForm;
$produtoForm->prepare();
$produtoForm->setAttribute('method', 'post');

$nome = $produtoForm->get('produtoLista');
$nome->setAttributes(['class' => 'form-control  text-dark']);
$nome->setAttributes(['placeholder' => 'fornecedor...']);
$nome->setAttributes(['required' => 'true']);

$quantidade = $produtoForm->get('quantidade');
$quantidade->setAttributes(['class' => 'form-control  text-dark']);
$quantidade->setAttributes(['placeholder' => 'quantidade...']);
$quantidade->setAttributes(['id' => 'quantidade']);
$quantidade->setAttributes(['required' => 'true']);

$send = $produtoForm->get('send');
$send->setAttributes(['class' => 'btn btn-primary float-right']);
$send->setAttributes(['id' => 'enviar']);


$listaForm = $this->listaForm;
$listaForm->prepare();
$listaForm->setAttribute('method', 'post');
// $listaForm->setAttribute('action', '/api/removerListaProduto');


$quantidade = $listaForm->get('quantidade');
$quantidade->setAttributes(['class' => 'form-control  text-dark']);
$quantidade->setAttributes(['placeholder' => 'quantidade...']);
$quantidade->setAttributes(['id' => 'quantidade']);
$quantidade->setAttributes(['required' => 'true']);


$sendLista = $listaForm->get('send');
$sendLista->setAttributes(['class' => 'btn btn-primary float-right']);
$sendLista->setAttributes(['id' => 'enviarLista']);

?>

<div class="col-12 row p-4" style="min-height: 400px;">
    <!-- <div class="col-xl-6 col-lg-12 ">
        <div class="card h-100  p-0 m-0 block-fixed">
            <div class="card-header row ">
                <div class="card-header col-10 ">
                    <h3 class="card-title"> Produtos </h3>
                </div>
                <div class="card-body ">
                    <div class="table-full-width table-responsive ">
                        <table class="table">
                            <tbody id="produtoTable">
                                <tr>
                                    <td>
                                        <p class="title">-</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <div class="col-12 ">
        <div class="card card-tasks h-100">
            <div class="card-header row">
                <div class="card-header col ">
                    <h3 class="card-title" id="forncededorTitle"> Lista </h3>
                </div>
                <div class="card-header col-3 mx-0 px-0">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#listaModal">
                        <i class="tim-icons icon-bag-16 tim-icons-lg"></i> PRODUTO +
                    </button>

                </div>
            </div>
            <div class="card-body">
                <div class="table-full-width table-responsive ">
                    <table class="table">
                        <tbody id="listaTable">
                            <tr>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>
                                <td>
                                    <p class="title">-</p>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                    <a href="/application/imprimirLista" target="_blank" class="btn btn-primary d-none" id="btnImprimir">IMPRIMIR</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12 row  p-4" style="min-height: 400px;" id="cardFornecedor">
    <div class="col-lg-12">
        <div class="card card-chart">
            <div class="card-header">
                <h3 class="card-title">MELHOR PREÇO</h3>
            </div>
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="CountryChart"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="listaModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="listaModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="listaModalLabel">Adicionar Na Lista</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <?= $this->form()->openTag($produtoForm); ?>
            <div class="modal-body">
                <div class="chart-area">
                    <div class="form-group">
                        <?= $this->formLabel($nome); ?>
                        <?= $this->formElement($nome); ?>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($quantidade); ?>
                        <?= $this->formElement($quantidade); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <?= $this->formElement($send); ?>
            </div>
            <?= $this->form()->closeTag(); ?>

        </div>
    </div>
</div>
<div class="modal fade" id="listaRemoverModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="listaRemoverModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="listaRemoverModalLabel">Remover da Lista</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <?= $this->form()->openTag($listaForm); ?>
            <input type="hidden" name="id" id="idProdutoLista">
            <div class="modal-body">
                <div class="chart-area">

                    <div class="form-group">
                        <?= $this->formLabel($quantidade); ?>
                        <?= $this->formElement($quantidade); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <?= $this->formElement($sendLista); ?>
            </div>
            <?= $this->form()->closeTag(); ?>

        </div>
    </div>
</div>



<script>
    var listaRemoverModal = new bootstrap.Modal(document.getElementById('listaRemoverModal'), {
        keyboard: false
    })
    var listaModal = new bootstrap.Modal(document.getElementById('listaModal'), {
        keyboard: false
    })


    $('#produtoForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('produtoForm')
        let formData = new FormData(form)
        let url = '/api/addListaProduto';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            console.log(e)
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#produtoForm input').val("");
                $('#enviar').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Produtos Cadastrados na Lista!',
                    'success'
                )
                loadFornecedores()
                loadProdutosLista()
                listaModal.hide()
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produtos Não Cadastrados na Lista!',
                    'error'
                )
            }

        }).fail(function(e) {
            console.log(e);
        });

    })
    $('#listaForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('listaForm')
        let formData = new FormData(form)
        let url = '/api/removerListaProduto';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#listaForm input').val("");
                $('#enviarLista').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Produtos Removidos da Lista!',
                    'success'
                )
                loadFornecedores()
                loadProdutosLista()
                listaRemoverModal.hide()
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produtos Não Removidos da Lista!',
                    'error'
                )
            }

        }).fail(function(e) {
            console.log(e);
        });

    })


    const loadProdutosLista = () => {
        $('#listaTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)
        let url = '/api/listaProduto';
        $.ajax({
            url: url,
            type: "POST",
        }).done(function(e) {
            let result = JSON.parse(e)

            console.log(result)

            $('#listaTable').html('')
            let total = 0
            let temDados = 0
            $('#listaTable').append(`<tr>
                            <td>
                                QTD
                            </td>
                            <td>
                                PRODUTO
                            </td>
                            <td>
                                MEDIDA
                            </td>
                            <td>
                                VALOR UNITÁRIO
                            </td>
                            <td>
                                VALOR TOTAL
                            </td>
                            <td>
                                FORNECEDOR
                            </td>
                            <td>
                            
                            </td>
                        </tr>`)
            result.map(produto => {
                temDados = 1
                let valor = ''
                let valorUnitario = 'R$' + produto.valor
                let totalProduto = produto.quantidade * produto.valor
                valor = 'R$' + totalProduto.toFixed(2)
                total = total + totalProduto
                $('#listaTable').append(`<tr>
                            <td>
                                ${produto.quantidade}
                            </td>
                            <td>
                                ${produto.nome}
                            </td>
                            <td>
                            ${produto.id_medida}
                            </td>
                            <td>
                                ${valorUnitario}
                            </td>
                            <td>
                                ${valor}
                            </td>
                            <td>
                            ${produto.fornecedor}
                            </td>
                            <td>
                            <i onclick="abrirlistaRemoverModal(${produto.id})" class="tim-icons text-danger icon-trash-simple tim-icons-lg click"></i>
                            </td>
                        </tr>`)
            })
            if (temDados == 1) {

                $('#listaTable').append(`<tr>
                <td>
                               
                            </td>
                            <td>
                                
                            </td>
                            <td>
                            
                            </td>
                            <td>
                                Total:
                            </td>

                            <td>
                            R$ ${total.toFixed(2)}
                            </td>
                            
                            <td>
                            
                            </td>
                            </tr>`)
                $('#btnImprimir').removeClass('d-none')
            }

        }).fail(function(e) {
            console.log(e);
        });
    }


    const abrirlistaRemoverModal = (id) => {
        $('#idProdutoLista').val(id)
        listaRemoverModal.show()
        console.log(id)
    }
    const loadFornecedores = () => {
        $('#listaTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)
        let url = '/api/listaProdutoFornecedor/1';
        $.ajax({
            url: url,
            type: "POST",
        }).done(function(e) {
            let result = JSON.parse(e)

            labels = new Array()
            dados = new Array()

            let maiorValor = 0
            result.map(fornecedor => {
                let valorFloat = parseFloat(fornecedor.valor).toFixed(2)

                labels.push(fornecedor.nome)
                dados.push(valorFloat);

                if (maiorValor < valorFloat) {
                    maiorValor = valorFloat
                }

            })

            gradientBarChartConfiguration = {
                maintainAspectRatio: false,
                legend: {
                    display: false
                },

                tooltips: {
                    backgroundColor: '#f5f5f5',
                    titleFontColor: '#333',
                    bodyFontColor: '#666',
                    bodySpacing: 4,
                    xPadding: 12,
                    mode: "nearest",
                    intersect: 0,
                    position: "nearest"
                },
                responsive: true,
                scales: {
                    yAxes: [{

                        gridLines: {
                            drawBorder: false,
                            color: 'rgba(29,140,248,0.1)',
                            zeroLineColor: "transparent",
                        },
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: maiorValor * 2,
                            padding: 20,
                            fontColor: "#9e9e9e"
                        }
                    }],

                    xAxes: [{

                        gridLines: {
                            drawBorder: false,
                            color: 'rgba(29,140,248,0.1)',
                            zeroLineColor: "transparent",
                        },
                        ticks: {
                            padding: 20,
                            fontColor: "#9e9e9e"
                        }
                    }]
                }
            };

            data = {
                labels: labels,
                datasets: [{
                    label: "",
                    fill: true,
                    backgroundColor: gradientStroke,
                    hoverBackgroundColor: gradientStroke,
                    borderColor: '#1f8ef1',
                    borderWidth: 2,
                    borderDash: [],
                    borderDashOffset: 0.0,
                    data: dados,
                }]
            }

            var ctx = document.getElementById("CountryChart").getContext("2d");

            var gradientStroke = ctx.createLinearGradient(0, 230, 0, 50);

            gradientStroke.addColorStop(1, 'rgba(29,140,248,0.2)');
            gradientStroke.addColorStop(0.4, 'rgba(29,140,248,0.0)');
            gradientStroke.addColorStop(0, 'rgba(29,140,248,0)'); //blue colors


            var myChart = new Chart(ctx, {
                type: 'bar',
                responsive: true,
                legend: {
                    display: false
                },
                data: data,
                options: gradientBarChartConfiguration
            });
        }).fail(function(e) {
            console.log(e);
        });
    }

    $(document).ready(function() {
        loadProdutosLista()
        loadFornecedores()
    });
</script>