<?php

$produtoForm = $this->produtoForm;
$produtoForm->prepare();
$produtoForm->setAttribute('method', 'post');

$nome = $produtoForm->get('nome');
$nome->setAttributes(['class' => 'form-control']);
$nome->setAttributes(['placeholder' => 'Produto...']);
$nome->setAttributes(['required' => 'true']);

$medida = $produtoForm->get('medida');
$medida->setAttributes(['class' => 'form-control']);
$medida->setAttributes(['required' => 'true']);

$categoria = $produtoForm->get('categoria');
$categoria->setAttributes(['class' => 'form-control']);
$categoria->setAttributes(['required' => 'true']);

$fornecedor = $produtoForm->get('fornecedor');
$fornecedor->setAttributes(['class' => 'form-control']);
$fornecedor->setAttributes(['required' => 'true']);

$quantidade = $produtoForm->get('quantidade');
$quantidade->setAttributes(['class' => 'form-control']);
$quantidade->setAttributes(['placeholder' => 'Quantidade...']);
$quantidade->setAttributes(['required' => 'true']);

$valor = $produtoForm->get('valor');
$valor->setAttributes(['class' => 'form-control']);
$valor->setAttributes(['placeholder' => 'Valor...']);
$valor->setAttributes(['required' => 'true']);

$send = $produtoForm->get('send');
$send->setAttributes(['class' => 'btn btn-primary float-right']);
$send->setAttributes(['id' => 'enviar']);
?>




<div class="col-md-12">
    <div class="card ">
        <div class="card-header row">
            <div class="card-header col-4 ">
                <h3 class="card-title"> Produtos </h3>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#produtoModal">
                    <i class="tim-icons icon-bag-16 tim-icons-lg"></i> PRODUTO +
                </button>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <i class="tim-icons icon-bullet-list-67 tim-icons-lg"></i> CATEGORIA +
                </button>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <i class="tim-icons icon-bus-front-12 tim-icons-lg"></i> FORNECEDOR +
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                            <th>
                                Nome
                            </th>
                            <th>
                                Medida
                            </th>
                            <th>
                                Quantidade
                            </th>
                            <th>
                                Preço
                            </th>
                            <th>
                                Fornecedor
                            </th>
                            <th>
                                Categoria
                            </th>
                        </tr>
                    </thead>
                    <tbody id="produtoTable">
                        <tr>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="produtoModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="produtoModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="transform: none;">
        <div class="modal-content">
            <?= $this->form()->openTag($produtoForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="produtoModalLabel">NOVO PRODUTO</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formLabel($nome); ?>
                    <?= $this->formElement($nome); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($medida); ?>
                    <?= $this->formElement($medida); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($quantidade); ?>
                    <?= $this->formElement($quantidade); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($valor); ?>
                    <?= $this->formElement($valor); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($categoria); ?>
                    <?= $this->formElement($categoria); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($fornecedor); ?>
                    <?= $this->formElement($fornecedor); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                <?= $this->formElement($send); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>

<script>
    const loadProduto = () => {
        $('#produtoTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)

        let url = 'http://' + window.location.host + '/api/produtos';
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#produtoTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            $('#produtoTable').html('')

            dados.map(produto => {
                $('#produtoTable').prepend(`<tr>
                            <td>
                                ${produto.nome}
                            </td>
                            <td>
                            ${produto.id_medida}
                            </td>
                            <td>
                            ${produto.quantidade}
                            </td>
                            <td>
                            R$ ${produto.valor}
                            </td>
                            <td>
                            ${produto.id_fornecedor}
                            </td>
                            <td>
                            ${produto.id_categoria}
                            </td>
                        </tr>`)
            })

        })

    }


    $(document).ready(() => {
        loadProduto()
    })
</script>