<?php

$fornecedorForm = $this->fornecedorForm;
$fornecedorForm->prepare();
$fornecedorForm->setAttribute('method', 'post');

$nomeFornecedor = $fornecedorForm->get('nome');
$nomeFornecedor->setAttributes(['class' => 'form-control  text-dark']);
$nomeFornecedor->setAttributes(['placeholder' => 'fornecedor...']);
$nomeFornecedor->setAttributes(['required' => 'true']);

$sendFornecedor = $fornecedorForm->get('send');
$sendFornecedor->setAttributes(['class' => 'btn btn-primary float-right']);
$sendFornecedor->setAttributes(['id' => 'enviarFornecedor']);


$categoriaForm = $this->categoriaForm;
$categoriaForm->prepare();
$categoriaForm->setAttribute('method', 'post');

$nomeCategoria = $categoriaForm->get('nome');
$nomeCategoria->setAttributes(['class' => 'form-control  text-dark']);
$nomeCategoria->setAttributes(['placeholder' => 'Categoria...']);
$nomeCategoria->setAttributes(['required' => 'true']);

$sendCategoria = $categoriaForm->get('send');
$sendCategoria->setAttributes(['class' => 'btn btn-primary float-right']);
$sendCategoria->setAttributes(['id' => 'enviarCategoria']);

$produtoForm = $this->produtoForm;
$produtoForm->prepare();
$produtoForm->setAttribute('method', 'post');

$nome = $produtoForm->get('nome');
$nome->setAttributes(['class' => 'form-control  text-dark']);
$nome->setAttributes(['placeholder' => 'Produto...']);
$nome->setAttributes(['required' => 'true']);

$medida = $produtoForm->get('medida');
$medida->setAttributes(['class' => 'form-control  text-dark']);
$medida->setAttributes(['required' => 'true']);

$categoria = $produtoForm->get('categoria');
$categoria->setAttributes(['class' => 'form-control  text-dark']);
$categoria->setAttributes(['required' => 'true']);

$fornecedor = $produtoForm->get('fornecedor');
$fornecedor->setAttributes(['class' => 'form-control  text-dark']);
$fornecedor->setAttributes(['required' => 'true']);

$quantidade = $produtoForm->get('quantidade');
$quantidade->setAttributes(['class' => 'form-control  text-dark']);
$quantidade->setAttributes(['placeholder' => 'Quantidade...']);
$quantidade->setAttributes(['required' => 'true']);

$valor = $produtoForm->get('valor');
$valor->setAttributes(['class' => 'form-control  text-dark']);
$valor->setAttributes(['placeholder' => 'Valor...']);
$valor->setAttributes(['id' => 'valor']);
$valor->setAttributes(['required' => 'true']);

$send = $produtoForm->get('send');
$send->setAttributes(['class' => 'btn btn-primary float-right']);
$send->setAttributes(['id' => 'enviar']);
?>




<div class="col-md-12">
    <div class="card ">
        <div class="card-header row">
            <div class="card-header col-4 ">
                <h3 class="card-title"> Produtos </h3>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#produtoModal">
                    <i class="tim-icons icon-bag-16 tim-icons-lg"></i> PRODUTO +
                </button>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#categoriaModal">
                    <i class="tim-icons icon-bullet-list-67 tim-icons-lg"></i> CATEGORIA +
                </button>
            </div>
            <div class="card-header col mx-0 px-0">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#fornecedorModal">
                    <i class="tim-icons icon-bus-front-12 tim-icons-lg"></i> FORNECEDOR +
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                            <th>
                                Nome
                            </th>
                            <th>
                                Medida
                            </th>
                            <th>
                                Quantidade
                            </th>
                            <th>
                                Preço
                            </th>
                            <th>
                                Fornecedor
                            </th>
                            <th>
                                Categoria
                            </th>
                        </tr>
                    </thead>
                    <tbody id="produtoTable">
                        <tr>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                            <td>
                                N/A
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="produtoModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="produtoModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="transform: none;">
        <div class="modal-content">
            <?= $this->form()->openTag($produtoForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="produtoModalLabel">NOVO PRODUTO</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formLabel($nome); ?>
                    <?= $this->formElement($nome); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($medida); ?>
                    <?= $this->formElement($medida); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($quantidade); ?>
                    <?= $this->formElement($quantidade); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($valor); ?>
                    <?= $this->formElement($valor); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($categoria); ?>
                    <?= $this->formElement($categoria); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($fornecedor); ?>
                    <?= $this->formElement($fornecedor); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                <?= $this->formElement($send); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="categoriaModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="categoriaModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?= $this->form()->openTag($categoriaForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="categoriaModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formLabel($nomeCategoria); ?>
                    <?= $this->formElement($nomeCategoria); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <?= $this->formElement($sendCategoria); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="fornecedorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="fornecedorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <?= $this->form()->openTag($fornecedorForm); ?>
            <div class="modal-header">
                <h5 class="modal-title" id="fornecedorModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <?= $this->formLabel($nomeFornecedor); ?>
                    <?= $this->formElement($nomeFornecedor); ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <?= $this->formElement($sendFornecedor); ?>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    var myModal = new bootstrap.Modal(document.getElementById('produtoModal'), {
        keyboard: false
    })
    const loadProduto = () => {
        $('#produtoTable').html(`<tr><td colspan='6'><center><div class="spinner-border" role="status">
                <span class="visually-hidden">Loading...</span>
                </div></center></td></tr>`)

        let url = '/api/produtos';
        $.ajax({
            url: url,
            type: 'GET',
            dataType: "json"
        }).fail((dados) => {
            $('#produtoTable').html(`<tr><td colspan='6'>ERROR</td></tr>`)

        }).done((dados) => {
            $('#produtoTable').html('')

            dados.map(produto => {
                $('#produtoTable').prepend(`<tr>
                            <td>
                                ${produto.nome}
                            </td>
                            <td>
                            ${produto.id_medida}
                            </td>
                            <td>
                            ${produto.quantidade}
                            </td>
                            <td>
                            R$ ${produto.valor}
                            </td>
                            <td>
                            ${produto.id_fornecedor}
                            </td>
                            <td>
                            ${produto.id_categoria}
                            </td>
                        </tr>`)
            })

        })

    }

    $('#produtoForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('produtoForm')
        let formData = new FormData(form)
        let url = '/api/insertProduto';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#produtoForm input').val("");
                $('#enviar').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Produto Cadastrado!',
                    'success'
                )
                myModal.hide()
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Produto Não Cadastrado!',
                    'error'
                )
            }

            loadProduto()
        }).fail(function(e) {
            console.log(e);
        });

    })
    $('#categoriaForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('categoriaForm')
        let formData = new FormData(form)
        let url = '/api/insertCategoria';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#categoriaForm input').val("");
                $('#enviarCategoria').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Categoria Cadastrada!',
                    'success'
                )
                myModal.hide()
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Categoria Não Cadastrada!',
                    'error'
                )
            }

            loadProduto()
        }).fail(function(e) {
            console.log(e);
        });

    })
    $('#fornecedorForm').submit(e => {
        e.preventDefault()
        let form = document.getElementById('fornecedorForm')
        let formData = new FormData(form)
        let url = '/api/insertFornecedor';
        $.ajax({
            url: url,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
        }).done(function(e) {
            let result = JSON.parse(e)
            if (result.success == 1) {
                $('#fornecedorForm input').val("");
                $('#enviarFornecedor').val("Enviar");
                Swal.fire(
                    'Eeeeee!',
                    'Fornecedor Cadastrado!',
                    'success'
                )
                myModal.hide()
            } else {
                Swal.fire(
                    'Aaaa!',
                    'Fornecedor Não Cadastrado!',
                    'error'
                )
            }

            loadProduto()
        }).fail(function(e) {
            console.log(e);
        });

    })


    $(document).ready(() => {

        loadProduto()
        $('#valor').maskMoney();
    })
</script>